[package]
name = "kabul_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-lite = "1.12.0"
glam = "0.23.0"
winit = "0.28.2"
wgpu = "0.15.1"